
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/program?useSSL=false&&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: msf731120


  mvc:
    view:
      perfix: /templates/
      suffix: .ftl

#mybatis:
#  mapper-locations: classpath*:/mappers/*.xml
#  type-aliases-package: com.duying.entity

