spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl


  datasource:
    url: jdbc:mysql://localhost:3306/program?useSSL=false&&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: msf731120
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
